package configurator

import (
	"bytes"
	"fmt"
	"io/ioutil"
	"os"
	"path/filepath"
	"strconv"
	"text/template"

	"github.com/NexusProtocol/forge-nexus/internal/prompt"
	"github.com/NexusProtocol/forge-nexus/pkg/deployer"
)

// Config holds the answers from the interactive configuration prompts.
type Config struct {
	P2P_ListenPort int
	RPC_ListenPort int
	NodeAlias      string
}

const defaultConfigTemplate = `# Default configuration for a Nexus node.
# Generated by The Forge SDK.

[p2p]
# Port for peer-to-peer communication
listen_port = {{.P2P_ListenPort}}

[rpc]
# Port for the RPC API
listen_port = {{.RPC_ListenPort}}

# A human-readable alias for your node (optional)
alias = "{{.NodeAlias}}"
`

// generateTOMLString creates a TOML configuration string from a Config struct.
func generateTOMLString(cfg Config) (string, error) {
	tmpl, err := template.New("config").Parse(defaultConfigTemplate)
	if err != nil {
		return "", fmt.Errorf("internal error: failed to parse config template: %w", err)
	}

	var buffer bytes.Buffer
	if err := tmpl.Execute(&buffer, cfg); err != nil {
		return "", fmt.Errorf("internal error: failed to execute config template: %w", err)
	}

	return buffer.String(), nil
}

// RunInteractive guides the user through creating a config file.
func RunInteractive(role string) error {
	fmt.Println("--- Interactive Node Configuration ---")
	fmt.Println("Please answer the following questions to create your config.toml.")
	fmt.Println("Press Enter to accept the default value in [brackets].")

	// 1. Gather input using the sovereign prompt
	alias := prompt.Ask("Enter a public alias for your node (optional)", "")
	p2pPortStr := prompt.Ask("Enter the P2P listening port", "8787")
	rpcPortStr := prompt.Ask("Enter the RPC listening port", "8788")

	// 2. Parse and validate input
	p2pPort, err := strconv.Atoi(p2pPortStr)
	if err != nil {
		return fmt.Errorf("invalid P2P port number: %s", p2pPortStr)
	}
	rpcPort, err := strconv.Atoi(rpcPortStr)
	if err != nil {
		return fmt.Errorf("invalid RPC port number: %s", rpcPortStr)
	}

	// 3. Populate the config struct
	cfg := Config{
		P2P_ListenPort: p2pPort,
		RPC_ListenPort: rpcPort,
		NodeAlias:      alias,
	}

	// 4. Generate the TOML content
	tomlContent, err := generateTOMLString(cfg)
	if err != nil {
		return err // Should be an internal error
	}

	// 5. Find the config path and write the file
	configPath, err := deployer.GetConfigPath(role)
	if err != nil {
		return fmt.Errorf("could not determine config path: %w", err)
	}
	// Ensure the directory exists before writing
	if err := os.MkdirAll(configPath, 0755); err != nil {
		return fmt.Errorf("could not create config directory: %w", err)
	}

	configFilePath := filepath.Join(configPath, "config.toml")
	fmt.Printf("\nWriting configuration to %s...\n", configFilePath)
	if err := ioutil.WriteFile(configFilePath, []byte(tomlContent), 0644); err != nil {
		return fmt.Errorf("failed to write config file: %w", err)
	}

	fmt.Println("✓ Configuration saved successfully.")
	return nil
}
